// category
export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY'
export const GET_PAGE_CATEGORY = 'GET_PAGE_CATEGORY'
export const CREATE_CATEGORY = 'CREATE_CATEGORY'
export const GET_ONE_CATEGORY = 'GET_ONE_CATEGORY'

// brand
export const GET_ALL_BRAND = 'GET_ALL_BRAND'
export const CREATE_BRAND = 'CREATE_BRAND'

// product
export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT'
export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const GET_ALL_PRODUCT_MORE_SALES = 'GET_ALL_PRODUCT_MORE_SALES'
export const GET_ALL_PRODUCT_LATEST = 'GET_ALL_PRODUCT_LATEST'
export const GET_PRODUCT_DETALIS = 'GET_PRODUCT_DETALIS'
export const GET_ALL_PRODUCT_LIKE = 'GET_ALL_PRODUCT_LIKE'
export const PRODUCT_DELETE = 'PRODUCT_DELETE'

// error
export const GET_ERROR = 'ERROR'
